# Generated by Django 2.2.6 on 2023-05-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_babies'),
    ]

    operations = [
        migrations.CreateModel(
            name='schooll_num',
            fields=[
                ('SIG_CD', models.IntegerField(primary_key=True, serialize=False)),
                ('행정구', models.FloatField()),
                ('일3년', models.FloatField()),
                ('일4년', models.FloatField()),
                ('일5년', models.FloatField()),
                ('일6년', models.FloatField()),
                ('일7년', models.FloatField()),
                ('일8년', models.FloatField()),
                ('일9년', models.FloatField()),
                ('일10년', models.FloatField()),
                ('일11년', models.FloatField()),
                ('일12년', models.FloatField()),
                ('일13년', models.FloatField()),
                ('일14년', models.FloatField()),
            ],
        ),
    ]
