# Generated by Django 2.2.6 on 2024-03-04 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20230522_1724'),
    ]

    operations = [
        migrations.DeleteModel(
            name='all_schools_by_year',
        ),
        migrations.DeleteModel(
            name='all_students_by_year',
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='BaBies',
        ),
        migrations.DeleteModel(
            name='Babyies',
        ),
        migrations.DeleteModel(
            name='R1',
        ),
        migrations.DeleteModel(
            name='R2',
        ),
        migrations.DeleteModel(
            name='R3',
        ),
        migrations.DeleteModel(
            name='R4',
        ),
        migrations.DeleteModel(
            name='R5',
        ),
        migrations.DeleteModel(
            name='R6',
        ),
        migrations.DeleteModel(
            name='RegionModel',
        ),
        migrations.DeleteModel(
            name='S',
        ),
        migrations.DeleteModel(
            name='school_num',
        ),
        migrations.DeleteModel(
            name='schooldata_by_professer',
        ),
        migrations.DeleteModel(
            name='schooldata_by_professer_babies',
        ),
        migrations.DeleteModel(
            name='schooldata_by_professer_close',
        ),
        migrations.DeleteModel(
            name='schooldata_by_statistics',
        ),
        migrations.DeleteModel(
            name='SchoolName',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
