# Generated by Django 2.2.6 on 2023-04-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_r1_r2_r3_r4_r5_r6'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('학교명', models.CharField(max_length=30)),
            ],
        ),
    ]
