from django.db import models

# Create your models here.

class RegionModel(models.Model):
    id = models.IntegerField(primary_key=True)
    학년구분 = models.CharField(max_length=30)
    학교명 = models.CharField(max_length=30)
    학교종류 = models.CharField(max_length=30)
    nt = models.FloatField()
    nnt = models.FloatField()
    nnnt = models.FloatField()
    행정구 = models.CharField(max_length=30)

class Students(models.Model):
    id = models.IntegerField(primary_key=True)
    학년구분 = models.CharField(max_length=30)
    학교명 = models.CharField(max_length=30)
    학교종류 = models.CharField(max_length=30)
    nt = models.FloatField()
    nnt = models.FloatField()
    nnnt = models.FloatField()
    행정구 = models.CharField(max_length=30)

class Babyies(models.Model):
    id = models.IntegerField(primary_key=True)
    출생년도 = models.FloatField()
    입학년도 = models.FloatField()
    ARIMA = models.FloatField()
    SSM = models.FloatField()
    DLDA = models.FloatField()

class B(models.Model):
    id = models.IntegerField(primary_key=True)
    출생년도 = models.FloatField()
    입학년도 = models.FloatField()
    ARIMA = models.FloatField()
    SSM = models.FloatField()
    DLDA = models.FloatField()

class S(models.Model):
    id = models.IntegerField(primary_key=True)
    학년구분 = models.CharField(max_length=30)
    학교명 = models.CharField(max_length=30)
    학교종류 = models.CharField(max_length=30)
    nt = models.FloatField()
    nnt = models.FloatField()
    nnnt = models.FloatField()
    행정구 = models.CharField(max_length=30)

class R1(models.Model):
    id = models.IntegerField(primary_key=True)
    예측년도 = models.FloatField()
    월배 = models.FloatField()
    성서 = models.FloatField()
    수성 = models.FloatField()
    칠곡 = models.FloatField()
    동부 = models.FloatField()
    서부 = models.FloatField()
    북부 = models.FloatField()
    남부 = models.FloatField()
    동대구 = models.FloatField()
    달성 = models.FloatField()
    중부 = models.FloatField()
    모델 = models.CharField(max_length=30)

class R2(models.Model):
    id = models.IntegerField(primary_key=True)
    예측년도 = models.FloatField()
    월배 = models.FloatField()
    성서 = models.FloatField()
    수성 = models.FloatField()
    칠곡 = models.FloatField()
    동부 = models.FloatField()
    서부 = models.FloatField()
    북부 = models.FloatField()
    남부 = models.FloatField()
    동대구 = models.FloatField()
    달성 = models.FloatField()
    중부 = models.FloatField()
    모델 = models.CharField(max_length=30)

class R3(models.Model):
    id = models.IntegerField(primary_key=True)
    예측년도 = models.FloatField()
    월배 = models.FloatField()
    성서 = models.FloatField()
    수성 = models.FloatField()
    칠곡 = models.FloatField()
    동부 = models.FloatField()
    서부 = models.FloatField()
    북부 = models.FloatField()
    남부 = models.FloatField()
    동대구 = models.FloatField()
    달성 = models.FloatField()
    중부 = models.FloatField()
    모델 = models.CharField(max_length=30)

class R4(models.Model):
    id = models.IntegerField(primary_key=True)
    예측년도 = models.FloatField()
    월배 = models.FloatField()
    성서 = models.FloatField()
    수성 = models.FloatField()
    칠곡 = models.FloatField()
    동부 = models.FloatField()
    서부 = models.FloatField()
    북부 = models.FloatField()
    남부 = models.FloatField()
    동대구 = models.FloatField()
    달성 = models.FloatField()
    중부 = models.FloatField()
    모델 = models.CharField(max_length=30)

class R5(models.Model):
    id = models.IntegerField(primary_key=True)
    예측년도 = models.FloatField()
    월배 = models.FloatField()
    성서 = models.FloatField()
    수성 = models.FloatField()
    칠곡 = models.FloatField()
    동부 = models.FloatField()
    서부 = models.FloatField()
    북부 = models.FloatField()
    남부 = models.FloatField()
    동대구 = models.FloatField()
    달성 = models.FloatField()
    중부 = models.FloatField()
    모델 = models.CharField(max_length=30)

class R6(models.Model):
    id = models.IntegerField(primary_key=True)
    예측년도 = models.FloatField()
    월배 = models.FloatField()
    성서 = models.FloatField()
    수성 = models.FloatField()
    칠곡 = models.FloatField()
    동부 = models.FloatField()
    서부 = models.FloatField()
    북부 = models.FloatField()
    남부 = models.FloatField()
    동대구 = models.FloatField()
    달성 = models.FloatField()
    중부 = models.FloatField()
    모델 = models.CharField(max_length=30)

class SchoolName(models.Model):
    id = models.IntegerField(primary_key=True)
    학교명 = models.CharField(max_length=30)

class BaBies(models.Model):
    id = models.IntegerField(primary_key=True)
    출생년도 = models.FloatField()
    입학년도 = models.FloatField()
    ARIMA = models.FloatField()
    SSM = models.FloatField()
    DLDA = models.FloatField()
    CRU = models.FloatField()

class school_num(models.Model):
    SIG_CD = models.IntegerField(primary_key=True)
    행정구 = models.CharField(max_length=30)
    일3년 = models.FloatField()
    일4년 = models.FloatField()
    일5년 = models.FloatField()
    일6년 = models.FloatField()
    일7년 = models.FloatField()
    일8년 = models.FloatField()
    일9년 = models.FloatField()
    일10년 = models.FloatField()
    일11년 = models.FloatField()
    일12년 = models.FloatField()
    일13년 = models.FloatField()
    일14년 = models.FloatField()

class schooldata_by_statistics(models.Model):
    id = models.IntegerField(primary_key=True)
    학교명 = models.CharField(max_length=30)
    중위통계청2023 = models.FloatField()
    중위통계청2024 = models.FloatField()
    중위통계청2025 = models.FloatField()
    중위통계청2026 = models.FloatField()
    중위통계청2027 = models.FloatField()
    중위통계청2028 = models.FloatField()
    중위통계청2029 = models.FloatField()
    중위통계청2030 = models.FloatField()
    중위통계청2031 = models.FloatField()
    중위통계청2032 = models.FloatField()
    중위통계청2033 = models.FloatField()
    중위통계청2034 = models.FloatField()
    중위통계청2035 = models.FloatField()
    중위통계청2036 = models.FloatField()
    중위통계청2037 = models.FloatField()
    중위통계청2038 = models.FloatField()
    중위통계청2039 = models.FloatField()
    중위통계청2040 = models.FloatField()
    중위통계청2041 = models.FloatField()
    중위통계청2042 = models.FloatField()
    저위통계청2023 = models.FloatField()
    저위통계청2024 = models.FloatField()
    저위통계청2025 = models.FloatField()
    저위통계청2026 = models.FloatField()
    저위통계청2027 = models.FloatField()
    저위통계청2028 = models.FloatField()
    저위통계청2029 = models.FloatField()
    저위통계청2030 = models.FloatField()
    저위통계청2031 = models.FloatField()
    저위통계청2032 = models.FloatField()
    저위통계청2033 = models.FloatField()
    저위통계청2034 = models.FloatField()
    저위통계청2035 = models.FloatField()
    저위통계청2036 = models.FloatField()
    저위통계청2037 = models.FloatField()
    저위통계청2038 = models.FloatField()
    저위통계청2039 = models.FloatField()
    저위통계청2040 = models.FloatField()
    저위통계청2041 = models.FloatField()
    저위통계청2042 = models.FloatField()
    무이동통계청2023 = models.FloatField()
    무이동통계청2024 = models.FloatField()
    무이동통계청2025 = models.FloatField()
    무이동통계청2026 = models.FloatField()
    무이동통계청2027 = models.FloatField()
    무이동통계청2028 = models.FloatField()
    무이동통계청2029 = models.FloatField()
    무이동통계청2030 = models.FloatField()
    무이동통계청2031 = models.FloatField()
    무이동통계청2032 = models.FloatField()
    무이동통계청2033 = models.FloatField()
    무이동통계청2034 = models.FloatField()
    무이동통계청2035 = models.FloatField()
    무이동통계청2036 = models.FloatField()
    무이동통계청2037 = models.FloatField()
    무이동통계청2038 = models.FloatField()
    무이동통계청2039 = models.FloatField()
    무이동통계청2040 = models.FloatField()
    무이동통계청2041 = models.FloatField()
    무이동통계청2042 = models.FloatField()
    구분 = models.CharField(max_length=5)

class schooldata_by_professer(models.Model):
    id = models.IntegerField(primary_key=True)
    학교명 = models.CharField(max_length=30)
    교수님2023 = models.FloatField()
    교수님2024 = models.FloatField()
    교수님2025 = models.FloatField()
    교수님2026 = models.FloatField()
    교수님2027 = models.FloatField()
    교수님2028 = models.FloatField()
    교수님2029 = models.FloatField()
    교수님2030 = models.FloatField()
    교수님2031 = models.FloatField()
    교수님2032 = models.FloatField()
    교수님2033 = models.FloatField()
    교수님2034 = models.FloatField()
    교수님2035 = models.FloatField()
    교수님2036 = models.FloatField()
    교수님2037 = models.FloatField()
    교수님2038 = models.FloatField()
    교수님2039 = models.FloatField()
    교수님2040 = models.FloatField()
    구분 = models.CharField(max_length=5)

class schooldata_by_professer_babies(models.Model):
    id = models.IntegerField(primary_key=True)
    출생년도 = models.FloatField()
    입학년도 = models.FloatField()
    통계청 = models.FloatField()
    ARIMA = models.FloatField()
    CRU = models.FloatField()
    SSM = models.FloatField()

class schooldata_by_professer_close(models.Model):
    id = models.IntegerField(primary_key=True)
    교수님2023 = models.FloatField()
    교수님2024 = models.FloatField()
    교수님2025 = models.FloatField()
    교수님2026 = models.FloatField()
    교수님2027 = models.FloatField()
    교수님2028 = models.FloatField()
    교수님2029 = models.FloatField()
    교수님2030 = models.FloatField()
    교수님2031 = models.FloatField()
    교수님2032 = models.FloatField()
    교수님2033 = models.FloatField()
    교수님2034 = models.FloatField()
    교수님2035 = models.FloatField()
    교수님2036 = models.FloatField()
    교수님2037 = models.FloatField()
    교수님2038 = models.FloatField()
    교수님2039 = models.FloatField()
    교수님2040 = models.FloatField()
    구분 = models.CharField(max_length=5)

class all_schools_by_year(models.Model):
    id = models.IntegerField(primary_key=True)
    년2016 = models.FloatField()
    년2017 = models.FloatField()
    년2018 = models.FloatField()
    년2019 = models.FloatField()
    년2020 = models.FloatField()
    년2021 = models.FloatField()
    년2022 = models.FloatField()

class all_students_by_year(models.Model):
    id = models.IntegerField(primary_key=True)
    년2010 = models.FloatField()
    년2011 = models.FloatField()
    년2012 = models.FloatField()
    년2013 = models.FloatField()
    년2014 = models.FloatField()
    년2015 = models.FloatField()
    년2016 = models.FloatField()
    년2017 = models.FloatField()
    년2018 = models.FloatField()
    년2019 = models.FloatField()
    년2020 = models.FloatField()
    년2021 = models.FloatField()