# Generated by Django 2.2.6 on 2023-04-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_schoolname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaBies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('출생년도', models.FloatField()),
                ('입학년도', models.FloatField()),
                ('ARIMA', models.FloatField()),
                ('SSM', models.FloatField()),
                ('DLDA', models.FloatField()),
                ('CRU', models.FloatField()),
            ],
        ),
    ]
