# Generated by Django 2.2.6 on 2023-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('출생년도', models.FloatField()),
                ('입학년도', models.FloatField()),
                ('ARIMA', models.FloatField()),
                ('SSM', models.FloatField()),
                ('DLDA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Babyies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('출생년도', models.FloatField()),
                ('입학년도', models.FloatField()),
                ('ARIMA', models.FloatField()),
                ('SSM', models.FloatField()),
                ('DLDA', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('학년구분', models.CharField(max_length=30)),
                ('학교명', models.CharField(max_length=30)),
                ('학교종류', models.CharField(max_length=30)),
                ('nt', models.FloatField()),
                ('nnt', models.FloatField()),
                ('nnnt', models.FloatField()),
                ('행정구', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='S',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('학년구분', models.CharField(max_length=30)),
                ('학교명', models.CharField(max_length=30)),
                ('학교종류', models.CharField(max_length=30)),
                ('nt', models.FloatField()),
                ('nnt', models.FloatField()),
                ('nnnt', models.FloatField()),
                ('행정구', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('학년구분', models.CharField(max_length=30)),
                ('학교명', models.CharField(max_length=30)),
                ('학교종류', models.CharField(max_length=30)),
                ('nt', models.FloatField()),
                ('nnt', models.FloatField()),
                ('nnnt', models.FloatField()),
                ('행정구', models.CharField(max_length=30)),
            ],
        ),
    ]
